function output = trainDynamicModel(params,monitor)
%% Experiment to train a Dynamic ROM model
% Train a ROM. Hyper-parameters for training are:
%%
% * |ModelType| - The type of ROM model to create
%

%   Copyright 2025-2026 The MathWorks, Inc.

dataFileName = 'trainingData.mat';
switch params.ModelType
    case romapp.internal.experimentmanager.DL.MLPExperiment.NAME
        data = load('trainingData.mat','LinearModelSizes');
        modelParams = struct(...
            'NumberLayers', 2, ...
            'HiddenLayerSize', romapp.internal.experimentmanager.QuickStart.approximateHiddenLayerSize(data.LinearModelSizes,2), ...
            'DataFileName', dataFileName);
        output = romapp.internal.experimentmanager.DL.trainMLP(modelParams,monitor);
    case romapp.internal.experimentmanager.DL.RNNExperiment.NAME
        data = load('trainingData.mat','SampleRate','LinearModelSizes');
        modelParams = struct(...
            'SampleRate', data.SampleRate, ...
            'NumberLayers', 2, ...
            'InitialLearnRate', 1e-3, ...
            'HiddenLayerSize', romapp.internal.experimentmanager.QuickStart.approximateHiddenLayerSize(data.LinearModelSizes,2), ...
            'DataFileName', dataFileName);
        output = romapp.internal.experimentmanager.DL.trainRNN(modelParams,monitor);
    case romapp.internal.experimentmanager.NLARX.NLARXExperiment.NAME
        data = load('trainingData.mat','SampleRate','LinearModelSizes');
        modelParams = struct(...
            'SampleRate', data.SampleRate, ...
            'ModelOrder', data.LinearModelSizes(3), ...
            'HiddenLayerSize', romapp.internal.experimentmanager.QuickStart.approximateHiddenLayerSize(data.LinearModelSizes,2), ...
            'DataFileName', dataFileName);
        output = romapp.internal.experimentmanager.NLARX.trainNLARX(modelParams,monitor);
    case romapp.internal.experimentmanager.NSS.NSSExperiment.NAME
        data = load('trainingData.mat','SampleRate','ModelLags','LinearModelSizes');
        modelParams = struct(...
            'SampleRate', data.SampleRate, ...
            'NumberLayers', 2, ...
            'NumberInputLags', data.ModelLags(2), ...
            'NumberOutputLags', data.ModelLags(1), ... 
            'HiddenLayerSize', romapp.internal.experimentmanager.QuickStart.approximateHiddenLayerSize(data.LinearModelSizes,2), ...
            'DataFileName', dataFileName);
        output = romapp.internal.experimentmanager.NSS.trainNSS(modelParams,monitor);
    case romapp.internal.experimentmanager.CascadeCorrelation.CascadeCorrelationExperiment.NAME
        data = load('trainingData.mat','SampleRate','LinearModelSizes');
        modelParams = struct(...
            'SampleRate', data.SampleRate, ...
            'ModelOrder', data.LinearModelSizes(3), ...
            'HiddenLayerSize', romapp.internal.experimentmanager.QuickStart.approximateHiddenLayerSize(data.LinearModelSizes,1), ...
            'DataFileName', dataFileName);
        output = romapp.internal.experimentmanager.CascadeCorrelation.trainCascadeCorrelation(modelParams,monitor);
    otherwise
        romapp.internal.resources.error('errEMQuickStart_InvalidModel',params.ModelType)
end
output.modelParams = modelParams;
end